third party api
iflytek/aiges pull request #44
Opened 2022-07-18 02:19 UTC by robbinlol

using python with third party api to realize wrapper

2022-07-18 07:54 UTC, berlinsaint commented
please config you git user. requires all commit messages to contain the Signed-off-by line with an email address that matches the commit author.

2022-07-18 09:40 UTC, robbinlol commented
add the config description.

2022-07-18 11:03 UTC, robbinlol commented
add the readme file.

2022-07-19 02:34 UTC, berlinsaint commented on demo/music_api/aiges.toml
> +<<<<<<< HEAD
resolve it.

2022-07-19 02:36 UTC, berlinsaint requested changes

2022-07-19 02:36 UTC, berlinsaint commented on demo/music_api/README.md
> +- 三方API的文档可以[参考](https://docs.acrcloud.cn/api-reference/identification-api/)
这里可以稍微加一些介绍性语言，介绍 这个加载器 加载三方api的目的是啥？为啥要用这个加载器，场景介绍。
不然用户会很模糊，不明所以

2022-07-19 07:36 UTC, robbinlol commented
解决了冲突，完善了README

2022-07-26 14:19 UTC, merged